### ISSUE TITLE
My volumes fail to be bound

### ISSUE THREAD

**Issue by griffins** [linode/linode-blockstorage-csi-driver#12] opened 2018-09-28 00:45 UTC
I provisioned a volume
```apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

Here is my describe pvc

```Name:          mysql-data
Namespace:     default
StorageClass:  linode-block-storage
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mysql-data","namespace":"default"},"spec":{"accessModes":["ReadW...
               volume.beta.kubernetes.io/storage-provisioner=com.linode.csi.linodebs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  ExternalProvisioning  3m (x41 over 13m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "com.linode.csi.linodebs" or manually created by system administrator
```

And my describe storageclass 

```Name:            linode-block-storage
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"linode-block-storage","namespace":""},"provisioner":"com.linode.csi.linodebs"}
,storageclass.kubernetes.io/is-default-class=true
Provisioner:        com.linode.csi.linodebs
Parameters:         <none>
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```  

What could be wrong?

**Comment by cliedeman** [comment] 2018-09-28 13:08
Hello

Can you attach the logs from the csi-attacher-linodeplugin and csi-provisioner-linodeplugin statefulsets?

**Comment by displague** [comment] 2019-03-02 14:39
@griffins Have you had any more recent attempts?  Your log messages would really assist in determining the cause here.

If the system hostname does not match the Linode label the driver will not be able to detect the correct Linode ID to attach the volume to.  Do your hostname and Linode label match?

**Comment by griffins** [comment] 2019-03-10 21:28
hi, I will find time to test the setup again this week and update you

**Comment by displague** [comment] 2019-03-11 11:40
@griffins The latest version, `v0.1.0` has other improvements over what you may have experienced in September/October. The last few versions have also added the requirement for Kubernetes 1.13+

https://github.com/linode/linode-blockstorage-csi-driver/releases

**Comment by displague** [comment] 2019-04-12 12:56
Closing this, @griffins.  Please reopen it if you encounter this problem again or have additional details.

**Closed by displague** 2019-04-12 12:56 UTC
